export const quotes = [
  "Your love is like a cup of hot cocoa on a chilly day—comforting and just what I need.",
  "I can't believe how lucky I am to have you. You make every day brighter with your love.",
  "You're not just my partner; you're my best friend. Your friendship means the world to me.",
  "Your hugs are like a warm embrace from the sun. They make everything better.",
  "Your smile is my favorite thing in the world. It's like a ray of sunshine on even the gloomiest days.",
  "Thank you for being my partner in crime and in love. Life with you is an adventure I cherish.",
  "Your love is like a lighthouse, guiding me through the storms and showing me the way.",
  "I love how you handle everything with such a positive attitude. You truly light up my world.",
  "You make our home feel like a haven, a place where love and warmth reside.",
  "Your love is like a gentle breeze, refreshing and always a breath of fresh air.",
  "Your laughter is the sweetest melody. It's my favorite sound in the whole wide world.",
  "Thank you for being the calm in my chaos, the anchor in my storms.",
  "Your kindness is like a ripple effect, spreading love and joy to everyone around you.",
  "I love the way you make me feel, like I'm the most important person in the world.",
  "Your love is my favorite kind of magic—a quiet enchantment that makes life extraordinary.",
  "You have this way of making ordinary moments feel extraordinary, and I love you for that.",
  "Thank you for being my partner on this crazy ride called life. I wouldn't want it any other way.",
  "Your love is like a constant, steady heartbeat. It's the rhythm of my life.",
  "Your presence is like a warm cup of tea, soothing and comforting in every way.",
  "I love how you make even the mundane moments special, turning the ordinary into extraordinary.",
  "Your love is like a secret garden—a place where beauty and tenderness bloom.",
  "Thank you for being my greatest supporter and cheerleader. Your encouragement means the world.",
  "Your love is the missing puzzle piece that completes the picture of my life.",
  "I appreciate how you never give up on us, even when things get tough. You're my rock.",
  "Your love is like a gentle rain, nourishing the soil of our relationship and making it blossom.",
  "You're not just my love; you're my home. With you, I'm always where I belong.",
  "Your wisdom and kindness inspire me to be a better person every day.",
  "Your love is like a cozy blanket, providing comfort and warmth on even the coldest days.",
  "Thank you for being the melody to my song, the lyrics to my love story.",
  "Your love is like a candle that never burns out, a constant source of light in my life.",
  "I love how you make every day an adventure, turning the ordinary into the extraordinary.",
  "Your laughter is infectious, and it's the best soundtrack to our love story.",
  "Your love is like a steady flame, warm and inviting, lighting up the darkest corners of my heart.",
  "Thank you for being my partner in crime, my confidant, and my greatest ally in life.",
  "Your love is like a gentle whisper, always there, comforting and reassuring.",
  "I appreciate how you make our house a home, filled with love, warmth, and laughter.",
  "Your love is like a compass, guiding me in the right direction and keeping me on course.",
  "You have this amazing ability to turn ordinary moments into extraordinary memories.",
  "Your kindness is like a gentle breeze, refreshing and making everything better.",
  "Thank you for being the anchor in my life, providing stability and support in every storm.",
  "Your love is like a well-tended garden, blossoming with beauty, tenderness, and joy.",
  "I love the way your eyes light up when you talk about the things you're passionate about.",
  "Your love is like a gentle rain, nurturing our relationship and helping it grow.",
  "You're not just my partner; you're my best friend, and I cherish every moment with you.",
  "Your smile is like a burst of sunshine, bringing warmth and happiness to my heart.",
  "Your love is like a warm embrace, comforting and reassuring, making everything feel alright.",
  "I appreciate how you make our home a haven, a place filled with love and understanding.",
  "Your love is like a sweet melody that plays in the background of my life, making everything better.",
  "Thank you for being the calm in my storm, the light in my darkness, and the love of my life.",
  "Your kindness is like a soothing balm, healing wounds and bringing comfort to my soul.",
  "I love the way you make even the simplest moments special, turning the ordinary into extraordinary.",
  "Your love is like a cup of hot cocoa, warm, comforting, and always a delight.",
  "You're not just my love; you're my safe haven, a place where I find comfort and peace.",
  "Your laughter is the sweetest melody, and it's the soundtrack to my happiest moments.",
  "Your love is like a steady flame, always burning bright, warming my heart in every way.",
  "Thank you for being my partner in this beautiful journey of life. I wouldn't want it any other way.",
  "Your love is like a gentle breeze, refreshing and making every moment better.",
  "I appreciate how you bring joy and laughter into our home, making it a place of happiness.",
  "Your love is like a constant, unwavering light, guiding me through the darkest of days.",
  "Your kindness is like a warm hug, comforting and reassuring, making everything feel alright.",
  "I love how you make our house a home, filled with love, laughter, and cherished moments.",
  "Thank you for being my anchor, providing stability and support through every storm.",
  "Your laughter is the sweetest sound, and it fills my heart with joy and happiness.",
  "Your love is like a cozy blanket, wrapping me in warmth and comfort on even the coldest days.",
  "You're not just my love; you're my best friend, confidant, and partner in all things.",
  "Your smile is like a burst of sunshine, bringing light and happiness into my world.",
  "Your love is like a soothing melody, calming my heart and bringing peace to my soul.",
  "Your love is my daily dose of happiness, making every moment special.",
  "I love you more than yesterday, but not as much as tomorrow.",
  "You're the peanut butter to my jelly, the perfect match in this crazy world.",
  "Thanks for being the sunshine in my life, brightening up even the cloudiest days.",
  "If love were a snowflake, I'd send you a blizzard every day.",
  "You're my favorite notification, and your love is my daily reminder of joy.",
  "Even on my worst days, your love is the silver lining that turns everything around.",
  "You're the missing piece in the puzzle of my heart, completing me in every way.",
  "Life with you is like a romantic comedy—full of laughter, love, and unexpected adventures.",
  "I love you more than coffee, and that's saying a latte!",
  "If love were a currency, I'd be the richest person alive because of you.",
  "You're my favorite kind of chaos, the beautiful mess that makes my heart skip a beat.",
  "Our love story is my favorite, and I can't wait to write more chapters with you.",
  "You're the MVP of my heart, scoring all the love points every single day.",
  "Our love is like a fine wine—it gets better with time.",
  "I love you to the moon and back, and then some more for good measure.",
  "You're the melody in my heart, playing a love song that never gets old.",
  "If kisses were snowflakes, I'd send you a blizzard every day.",
  "You're the reason my heart smiles, and I'm grateful for you every day.",
  "Our love is like a cozy blanket, wrapping us in warmth and comfort.",
  "I'm not a photographer, but I can definitely picture us together forever.",
  "You're the peanut to my butter, the jelly to my sandwich, and the love of my life.",
  "I love you more than a pizza delivery on a lazy Sunday—now that's saying something!",
  "You're the WiFi to my heart, connecting us in ways words can't describe.",
  "I love you not only for who you are but for who I am when I'm with you.",
  "Our love is like a well-organized closet—neat, tidy, and filled with endless possibilities.",
  "If love were a language, ours would be my favorite dialect.",
  "I love you more than a puppy loves belly rubs, and that's saying a lot!",
  "You're the sweetener in my coffee, making life extra delightful.",
  "You're the icing on the cake of my life, making everything sweeter.",
  "Our love is like a perfectly brewed cup of tea—warm, comforting, and just right.",
  "If love were a superhero, you'd be my caped crusader, saving me from the mundane.",
  "You're the GPS in the journey of my life, guiding me to happiness every day.",
  "I love you more than a sloth loves a leisurely nap, and that's saying something!",
  "Our love is like a fine-tuned playlist—full of beautiful notes that resonate in our hearts.",
  "You're the marshmallow in my hot cocoa, making every moment extra cozy.",
  "If love were a game, I'd play on your team forever.",
  "You're the avocado to my toast, the perfect pairing in this crazy world.",
  "I love you more than a cat loves a cardboard box, and that's saying a whiskerful!",
  "Our love is like a garden, constantly blooming with new and beautiful surprises.",
  "You're the star in my night sky, shining brightly and lighting up my world.",
  "If love were a dance, I'd choose to waltz through life with you.",
  "You're the sprinkles on my ice cream, adding joy and sweetness to my life.",
  "I love you more than a bee loves honey, and that's saying a buzzworthy lot!",
  "Our love is like a cozy winter fire, warming us with its comforting glow.",
  "You're the key to my heart, unlocking love and happiness with every beat.",
  "If love were a book, ours would be a bestseller with a never-ending story.",
  "You're the sunshine on my rainy days, brightening even the darkest moments.",
  "I love you more than a plant loves sunlight, and that's saying a photosynthesizing lot!",
  "Our love is like a perfectly crafted latte—rich, creamy, and always satisfying.",
  "I love you more than a penguin loves sliding on ice, and that's saying something chilly!",
  "You're the joy in my laughter, the sparkle in my eyes, and the love in my heart.",
  "If love were a journey, I'd choose the scenic route with you by my side.",
  "I love you more than a rainbow loves its colors, and that's saying something vibrant!",
  "You're the sunshine on my cloudy days, bringing warmth and brightness into my life.",
  "If love were a fragrance, ours would be my favorite scent.",
  "I love you more than a koala loves eucalyptus, and that's saying something eucalyptical!",
  "Your love is a gentle breeze that soothes my soul and calms the storms within.",
  "In the symphony of life, your love is the melody that makes every note meaningful.",
  "Our love has weathered storms and emerged stronger, like a resilient oak tree.",
  "You're the poetry written in the margins of my life, making each moment profound.",
  "Our connection is not just a spark but a flame that burns steadily, warming our hearts.",
  "Your touch is a masterpiece, painting emotions on the canvas of my skin.",
  "In the vast ocean of emotions, your love is the anchor that keeps me grounded.",
  "Our love story is a vintage wine, maturing with time and becoming richer each day.",
  "You're the serendipity that gracefully entered my life, turning it into a beautiful journey.",
  "Our love is not a sprint but a marathon, enduring and rewarding with every step.",
  "Like a fine aged whiskey, our love has depth, complexity, and an exquisite taste.",
  "You are the chapter I never knew my story needed, making the narrative complete.",
  "In the silence of the night, your presence speaks volumes, bringing comfort and peace.",
  "Our love is a sanctuary, a place where we find solace and understanding.",
  "You're the sunrise after the darkest night, bringing hope and a new beginning.",
  "Your gaze is a compass, guiding me through life's uncertainties with unwavering certainty.",
  "Our love is an unspoken language, understood deeply without the need for words.",
  "Like a well-worn book, our love has pages filled with memories, dog-eared with affection.",
  "You're the calm melody in the chaos of life, a soothing song that resonates within me.",
  "Our journey together is not just a destination but a meaningful exploration of the soul.",
  "Your love is the tapestry that weaves warmth and tenderness into the fabric of my existence.",
  "In the mosaic of emotions, your love is the intricate pattern that makes life beautiful.",
  "Our love is a sculpture, crafted with care and shaped by shared experiences and emotions.",
  "You're the silent whisper in my heart, echoing the sweetest words of love and devotion.",
  "Like a well-played sonata, our love harmonizes in perfect balance and timeless elegance.",
  "Our connection is not just a thread but a tapestry, woven with threads of trust and intimacy.",
  "You're the constant in the changing seasons of life, a reassuring presence in every moment.",
  "Your love is the portrait that captures the essence of my being, hanging prominently in my heart.",
  "In the vast expanse of time, our love is a timeless masterpiece, standing strong and true.",
  "You're the lighthouse in the darkness, guiding me through the uncertainties of life.",
  "Our love is a carefully tended garden, blossoming with the flowers of joy, passion, and understanding.",
  "Like a well-aged wine, our love has mellowed into a deep and satisfying connection.",
  "You're the beacon of hope that shines even in the darkest hours, lighting the path ahead.",
  "Our love is an eloquent silence, where words are unnecessary, and understanding prevails.",
  "Your love is the foundation of my strength, providing stability and support in every circumstance.",
  "In the gallery of emotions, our love is an exquisite masterpiece, admired by the heart.",
  "You're the echo in my soul, resonating with the love that binds us together.",
  "Our love is a sacred covenant, a commitment written in the stars and sealed in our hearts.",
  "Like a well-crafted novel, our love unfolds with each chapter, revealing new depths and dimensions.",
  "You are the essence of my joy, the melody in my heart, and the reason for my every smile.",
  "Our love is a timeless melody, playing softly in the background of our shared moments.",
  "You're the symphony of my heart, a composition that echoes in the chambers of my soul.",
  "In the canvas of life, your love is the brushstroke that adds color and meaning to every scene.",
  "Our love is a sanctuary, a haven where we find refuge in each other's embrace.",
  "You're the compass that guides me through the intricate maze of life, leading me to you.",
  "Like a classic novel, our love stands the test of time, with each chapter marked by resilience and grace.",
  "Our connection is not just a bond but an unbreakable chain, forged in the fires of shared experiences.",
  "You're the fragrance that lingers in the air, leaving a trail of love wherever you go.",
  "In the tapestry of time, our love is a golden thread that weaves through every moment.",
  "Your love is the gentle rain that nourishes the soil of our relationship, allowing our love to bloom.",
  "Our journey together is not just a path but an adventure, filled with twists, turns, and shared laughter.",
  "You're the anchor that keeps me grounded in the stormy seas of life, providing stability and strength.",
  "Like a timeless masterpiece, our love is a work of art, appreciated by those who see its beauty.",
  "Our love is a melody that plays in the silence, a sweet song that resonates in the heart.",
  "You're the sun that brightens my darkest days, bringing warmth and light to my world.",
  "In the quiet moments, your love is the gentle whisper that reassures and comforts my soul.",
  "Our connection is not just a bond but a lifeline, connecting us through the ebb and flow of life.",
  "You're the serenade in my heart, a melody that plays softly in the background of my thoughts.",
  "Like a well-worn path, our love is a journey traveled together, with every step etched in our hearts.",
  "Our love is a gentle flame that burns bright, casting away the shadows and illuminating our path.",
  "You're the compass of my heart, guiding me with unwavering certainty in the direction of love.",
  "In the gallery of emotions, our love is an exquisite painting, capturing the beauty of shared moments.",
  "Your love is the calm in my storm, the sanctuary where I find peace amidst life's chaos.",
  "Our love is a tapestry woven with threads of joy, sorrow, and the shared experiences that define us.",
  "You're the timeless melody that plays in the background of my life, creating a soundtrack of love.",
  "Like a well-written script, our love is a story filled with twists, turns, and a happily-ever-after.",
  "Our connection is not just a thread but a lifeline, binding us together through the highs and lows.",
  "You're the sunrise that paints the sky with hues of warmth, signaling a new day of love.",
  "In the tapestry of life, your love is the golden thread that adds brilliance to every moment.",
  "Our love is a sanctuary, a place where we find solace, understanding, and unwavering support.",
  "You're the melody in my heart, the rhythm that beats in sync with the music of our love.",
  "Like a well-crafted novel, our love story unfolds with each chapter, revealing new depths and dimensions.",
  "Your love is like a cozy blanket, warming my heart on the coldest days.",
  "I'm grateful for each beat of your heart, syncing perfectly with mine.",
  "You're the peanut butter to my jelly, the perfect match in every way.",
  "Our love story is my favorite, filled with plot twists and heartwarming moments.",
  "Your smile is the GPS that leads me to happiness every single day.",
  "I love you more than a pizza delivery on a Friday night.",
  "You're the missing piece to my puzzle, completing the picture of my life.",
  "Our love is like a fine wine, getting better with each passing year.",
  "I'm so in love with you that I would share my fries without any regrets.",
  "You're the marshmallow in my hot chocolate, making life sweet and warm.",
  "If love were a currency, we'd be the wealthiest couple in the world.",
  "You're my sunshine on a cloudy day, brightening up even the darkest moments.",
  "Our love is like a well-crafted joke; it gets better with every retelling.",
  "Your love is my favorite song, and I never want the music to end.",
  "Our love is like a roller coaster; it has its ups and downs, but it's always thrilling.",
  "You're the WiFi to my internet – without you, everything is disconnected.",
  "If our love were a movie, it would be a romantic comedy with a happy ending.",
  "You're the star in the movie of my life, and I wouldn't want it any other way.",
  "Our love is like a good book; I can't put it down, and I never want it to end.",
  "You're the icing on my cupcake, making life's moments even more delicious.",
  "If love were a crime, I'd be serving a life sentence with you.",
  "Our love is like a cozy winter fireplace, warming us from the inside out.",
  "You're the GPS to my lost heart, guiding me back whenever I'm lost.",
  "You're the chocolate to my fondue – sweet, irresistible, and always melting my heart.",
  "Our love is like a garden, constantly growing and blooming with beauty.",
  "If love were a dance, ours would be a never-ending, magical waltz.",
  "You're the light at the end of my tunnel, leading me to brighter days.",
  "Our love is like a handwritten letter – personal, timeless, and filled with emotion.",
  "You're the melody to my heart's song, playing in perfect harmony.",
  "If our love were a dessert, it would be a never-ending buffet of sweetness.",
  "You're the superhero in my story, saving me from life's challenges.",
  "Our love is like a cup of coffee – strong, comforting, and always a pick-me-up.",
  "You're the key to my heart, unlocking the door to endless love.",
  "If love were a color, ours would paint the most beautiful rainbow.",
  "You're the warmth in my hug, making me feel safe and loved.",
  "Our love is like a symphony, each note blending to create a masterpiece.",
  "You're the sprinkles on my ice cream, making life's moments even more delightful.",
  "If love were a language, ours would be a beautiful, never-ending conversation."
];