export const quotes = [
    "Your love is like a cup of hot cocoa on a chilly day—comforting and just what I need.",
    "I can't believe how lucky I am to have you. You make every day brighter with your love.",
    "You're not just my partner; you're my best friend. Your friendship means the world to me.",
    "Your hugs are like a warm embrace from the sun. They make everything better.",
    "Your smile is my favorite thing in the world. It's like a ray of sunshine on even the gloomiest days.",
    "Thank you for being my partner in crime and in love. Life with you is an adventure I cherish.",
    "Your love is like a lighthouse, guiding me through the storms and showing me the way.",
    "I love how you handle everything with such a positive attitude. You truly light up my world.",
    "You make our home feel like a haven, a place where love and warmth reside.",
    "Your love is like a gentle breeze, refreshing and always a breath of fresh air.",
    "Your laughter is the sweetest melody. It's my favorite sound in the whole wide world.",
    "Thank you for being the calm in my chaos, the anchor in my storms.",
    "Your kindness is like a ripple effect, spreading love and joy to everyone around you.",
    "I love the way you make me feel, like I'm the most important person in the world.",
    "Your love is my favorite kind of magic—a quiet enchantment that makes life extraordinary.",
    "You have this way of making ordinary moments feel extraordinary, and I love you for that.",
    "Thank you for being my partner on this crazy ride called life. I wouldn't want it any other way.",
    "Your love is like a constant, steady heartbeat. It's the rhythm of my life.",
    "Your presence is like a warm cup of tea, soothing and comforting in every way.",
    "I love how you make even the mundane moments special, turning the ordinary into extraordinary.",
    "Your love is like a secret garden—a place where beauty and tenderness bloom.",
    "Thank you for being my greatest supporter and cheerleader. Your encouragement means the world.",
    "Your love is the missing puzzle piece that completes the picture of my life.",
    "I appreciate how you never give up on us, even when things get tough. You're my rock.",
    "Your love is like a gentle rain, nourishing the soil of our relationship and making it blossom.",
    "You're not just my love; you're my home. With you, I'm always where I belong.",
    "Your wisdom and kindness inspire me to be a better person every day.",
    "Your love is like a cozy blanket, providing comfort and warmth on even the coldest days.",
    "Thank you for being the melody to my song, the lyrics to my love story.",
    "Your love is like a candle that never burns out, a constant source of light in my life.",
    "I love how you make every day an adventure, turning the ordinary into the extraordinary.",
    "Your laughter is infectious, and it's the best soundtrack to our love story.",
    "Your love is like a steady flame, warm and inviting, lighting up the darkest corners of my heart.",
    "Thank you for being my partner in crime, my confidant, and my greatest ally in life.",
    "Your love is like a gentle whisper, always there, comforting and reassuring.",
    "I appreciate how you make our house a home, filled with love, warmth, and laughter.",
    "Your love is like a compass, guiding me in the right direction and keeping me on course.",
    "You have this amazing ability to turn ordinary moments into extraordinary memories.",
    "Your kindness is like a gentle breeze, refreshing and making everything better.",
    "Thank you for being the anchor in my life, providing stability and support in every storm.",
    "Your love is like a well-tended garden, blossoming with beauty, tenderness, and joy.",
    "I love the way your eyes light up when you talk about the things you're passionate about.",
    "Your love is like a gentle rain, nurturing our relationship and helping it grow.",
    "You're not just my partner; you're my best friend, and I cherish every moment with you.",
    "Your smile is like a burst of sunshine, bringing warmth and happiness to my heart.",
    "Your love is like a warm embrace, comforting and reassuring, making everything feel alright.",
    "I appreciate how you make our home a haven, a place filled with love and understanding.",
    "Your love is like a sweet melody that plays in the background of my life, making everything better.",
    "Thank you for being the calm in my storm, the light in my darkness, and the love of my life.",
    "Your kindness is like a soothing balm, healing wounds and bringing comfort to my soul.",
    "I love the way you make even the simplest moments special, turning the ordinary into extraordinary.",
    "Your love is like a cup of hot cocoa, warm, comforting, and always a delight.",
    "You're not just my love; you're my safe haven, a place where I find comfort and peace.",
    "Your laughter is the sweetest melody, and it's the soundtrack to my happiest moments.",
    "Your love is like a steady flame, always burning bright, warming my heart in every way.",
    "Thank you for being my partner in this beautiful journey of life. I wouldn't want it any other way.",
    "Your love is like a gentle breeze, refreshing and making every moment better.",
    "I appreciate how you bring joy and laughter into our home, making it a place of happiness.",
    "Your love is like a constant, unwavering light, guiding me through the darkest of days.",
    "Your kindness is like a warm hug, comforting and reassuring, making everything feel alright.",
    "I love how you make our house a home, filled with love, laughter, and cherished moments.",
    "Your love is like a sweet melody that plays in the background of my life, making everything better.",
    "Thank you for being my anchor, providing stability and support through every storm.",
    "Your laughter is the sweetest sound, and it fills my heart with joy and happiness.",
    "Your love is like a cozy blanket, wrapping me in warmth and comfort on even the coldest days.",
    "You're not just my love; you're my best friend, confidant, and partner in all things.",
    "Your smile is like a burst of sunshine, bringing light and happiness into my world.",
    "Your love is like a soothing melody, calming my heart and bringing peace to my soul.",
    "I appreciate how you make our home a haven, a place filled with love and understanding.",
    "Your love is like a well-tended garden, blossoming with beauty, tenderness, and joy.",
    "Thank you for being the calm in my storm, the light in my darkness, and the love of my life.",
    "Your kindness is like a soothing balm, healing wounds and bringing comfort to my soul.",
    "I love the way you make even the simplest moments special, turning the ordinary into extraordinary."
  ];